services:
  maven-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ~/.m2:/root/.m2
    working_dir: /app
    command: mvn clean install
    stdin_open: true
    tty: true
